spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activitispringboot?characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
server:
  port: 9932