spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect

  datasource:
    url: jdbc:oracle:thin:@192.168.3.77:1521:orcl
    username: NKY
    password: nky
    driverClassName: oracle.jdbc.driver.OracleDriver
  activiti:
    check-process-definitions: false
server:
  port: 9904