spring:
  thymeleaf:
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
    cache: false
    mode: LEGACYHTML5
  datasource:
    url: jdbc:oracle:thin:@192.168.3.71:1521:orcl
    username: c##activiti
    password: activiti
    driverClassName: oracle.jdbc.driver.OracleDriver
  dubbo:
    application:
      name: activiConsumer
    registry:
      address: zookeeper://127.0.0.1:2181
      timeout: 1200000
    scan: com.scxys
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      indent-output: false
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
  activiti:
    check-process-definitions: false
server:
  port: 9907