spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/activitispringboot?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9916
logging:
  level: debug