spring:
  dubbo:
    application:
      name: activiProvider
    registry:
      address: zookeeper://127.0.0.1:2181
      timeout: 1200000
    protocol:
      name: dubbo
      port: 20882
    scan: com.scxys
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/activitispringboot?characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
    check-process-definitions: false

server:
  port: 9904