spring:
  dubbo:
    application:
      name: activiProvider
    registry:
      address: zookeeper://127.0.0.1:2181
      timeout: 1200000
    protocol:
      name: dubbo
      port: 20882
    scan: com.scxys
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect

  datasource:
     url: jdbc:oracle:thin:@192.168.10.240:1521:orcl
     username: system
     password: Oracle123
     driverClassName: oracle.jdbc.driver.OracleDriver
  activiti:
    check-process-definitions: false

server:
  port: 9904