spring:
  dubbo:
    application:
      name: activiProvider
    registry:
      address: zookeeper://127.0.0.1:2181
      timeout: 1200000
    protocol:
      name: dubbo
      port: 20882
    scan: com.scxys
  jpa:
    hibernate:
      ddl-auto: update
    database: oracle
    show-sql: true
  datasource:
    url: jdbc:oracle:thin:@192.168.3.71:1521:orcl
    username: c##activiti
    password: activiti
    driver-class-name: oracle.jdbc.driver.OracleDriver
  activiti:
    check-process-definitions: false

server:
  port: 9904